quiet: true
compact: true
framework:
  - terraform
skip-check:
  - CKV2_AZURE_33   # private endpoint — lab cost
  - CKV2_AZURE_38   # soft delete
  - CKV2_AZURE_40   # shared key auth
  - CKV2_AZURE_41   # SAS expiration
  - CKV_AZURE_244   # local user SFTP
  - CKV2_AZURE_1    # CMK encryption — lab, not production
  - CKV_AZURE_206   # GRS replication — lab cost
  - CKV_AZURE_33    # Queue logging — not using queues